# Generated by Django 4.1.3 on 2022-11-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(to="users.user"),
        ),
    ]
